# Generated by Django 3.2 on 2023-03-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0002_auto_20230319_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, max_length=1, verbose_name='Sex'),
        ),
    ]
