# Generated by Django 3.2 on 2023-03-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0003_alter_usermodel_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='typ',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Company')], default=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1, verbose_name='Sex'),
        ),
    ]
