# Generated by Django 3.2 on 2023-05-24 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_usermodel_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_staff',
        ),
    ]
