# Generated by Django 3.2 on 2023-03-27 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_auto_20230327_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='users/banners/', verbose_name='Banner'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='count_type',
            field=models.IntegerField(blank=True, choices=[(1, '1-10'), (2, '10-50'), (3, '50-200'), (4, '200-1000'), (5, '+1000')], null=True, verbose_name='Count type'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='education_degree',
            field=models.IntegerField(blank=True, choices=[(1, 'Associate'), (2, 'Bachelor'), (3, 'Master'), (4, 'Doctoral')], default=1, null=True, verbose_name='Education Degree'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='educations',
            field=models.TextField(blank=True, null=True, verbose_name='Educations'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='establishment',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1300), django.core.validators.MaxValueValidator(1403)], verbose_name='Establishment'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='experiences',
            field=models.TextField(blank=True, null=True, verbose_name='Experiences'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='languages',
            field=models.TextField(blank=True, null=True, verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name_en',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='English name'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name_fa',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Persian name'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='old',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(65)], verbose_name='Old'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1, null=True, verbose_name='Sex'),
        ),
    ]
