# Generated by Django 3.2 on 2023-03-29 08:37

import apps.share.validators.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_auto_20230327_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[apps.share.validators.user.MobileValidator()], verbose_name='Mobile'),
        ),
    ]
