# Generated by Django 3.2 on 2023-03-31 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('share', '0002_auto_20230331_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('typ', models.IntegerField(choices=[(0, 'Full Time'), (1, 'Part Time'), (2, 'Remote')], default=0, verbose_name='Type of cooperation')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Salary')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Skills')),
                ('educations', models.TextField(blank=True, null=True, verbose_name='Educations')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About')),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], default=1, null=True, verbose_name='Sex')),
                ('military_status', models.IntegerField(choices=[(0, 'Included'), (1, 'Done'), (2, 'Exempt'), (3, 'No Matter')], default=3, verbose_name='Military Status')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobcategorymodel', verbose_name='Categories')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='share.citymodel', verbose_name='City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Company')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
