# Generated by Django 3.2 on 2023-04-01 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0003_jobapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplication',
            new_name='JobApplicationModel',
        ),
    ]
