# Generated by Django 3.2 on 2023-04-01 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0004_rename_jobapplication_jobapplicationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationmodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='job.jobmodel', verbose_name='Job'),
        ),
        migrations.AlterField(
            model_name='jobapplicationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
